import {useEffect,useRef,useState} from 'react'
import {useAppContext} from '../App'
import SectorAvatar from '../components/sector/SectorAvatar'
import SectorFeatureArt, { StoryPathArt } from '../components/sector/SectorFeatureArt'
import SectorLongGame from '../components/sector/SectorLongGame'
import SectorPetSkeleton from '../components/sector/SectorPetSkeleton'
import SectorShareCard from '../components/sector/SectorShareCard'
import SectorIcon from '../components/ui/SectorIcon'
import {ActionArt,ShopItemArt,StickerArt} from '../components/sector/SectorVisuals'
import {feedback} from '../utils/feedback'

const CARE={charge:'شارژ انرژی',play:'بازی',train:'تمرین',learn:'یادگیری',repair:'تعمیر',feed:'غذا دادن',clean:'تمیزکاری',sleep:'استراحت'}
const STATS=[['energy','انرژی'],['happiness','شادی'],['hunger','سیری'],['cleanliness','نظافت'],['health','سلامت'],['knowledge','دانش']]
const TABS=[['home','خانه'],['care','مراقبت'],['shop','فروشگاه'],['growth','رشد'],['season','فصل'],['games','بازی'],['social','اجتماع'],['memories','خاطرات'],['talk','گفتگو']]
function Bar({icon,label,value,max=100}){const n=Math.max(0,Math.min(100,Number(value||0)/Math.max(1,max)*100));return <div className="sector-stat"><div className="sector-stat__label"><span><SectorIcon name={icon} size={14}/>{label}</span><b>{Math.round(Number(value||0))}</b></div><div className="progress-bar"><div className="progress-fill" style={{width:n+'%'}}/></div></div>}
function Stage({stage}){const ids=['scrap','patched','core','advanced','elite','mythic'],i=Math.max(0,ids.indexOf(stage?.id));return <div className="glass" style={{padding:12}}><div style={{display:'flex',justifyContent:'space-between'}}><b>{stage?.title||'Scrap Unit'}</b><span style={{fontSize:9,color:stage?.accent}}>{stage?.condition||'فرسوده'}</span></div><div style={{display:'grid',gridTemplateColumns:'repeat(6,1fr)',gap:4,marginTop:10}}>{ids.map((x,n)=><div key={x} style={{height:5,borderRadius:5,background:n<=i?'#7486ff':'rgba(255,255,255,.08)'}}/>)}</div></div>}
function Empty({children}){return <div style={{padding:20,textAlign:'center',fontSize:10,color:'var(--muted)'}}>{children}</div>}
function MemoryGame({done}){const [seq,setSeq]=useState([]),[input,setInput]=useState([]),[active,setActive]=useState(-1),[run,setRun]=useState(false),timers=useRef([]);function clear(){timers.current.forEach(clearTimeout);timers.current=[]}useEffect(()=>clear,[]);function flash(s){clear();setRun(false);setInput([]);s.forEach((x,i)=>{timers.current.push(setTimeout(()=>setActive(x),300+i*550));timers.current.push(setTimeout(()=>setActive(-1),610+i*550))});timers.current.push(setTimeout(()=>setRun(true),350+s.length*550))}function start(){const s=[0,1,2].map(()=>Math.floor(Math.random()*4));setSeq(s);flash(s)}function tap(x){if(!run)return;const n=[...input,x];setInput(n);if(seq[n.length-1]!==x){setRun(false);done('circuit',Math.max(10,(seq.length-3)*20));return}if(n.length===seq.length){if(seq.length>=8){setRun(false);done('circuit',100)}else{const s=[...seq,Math.floor(Math.random()*4)];setSeq(s);setTimeout(()=>flash(s),450)}}}return <div className="glass" style={{padding:14}}><div style={{display:'flex',alignItems:'center',gap:8}}><StickerArt kind="mission" compact/><div><b>مدار حافظه</b><p style={{fontSize:9,color:'var(--muted)',margin:'4px 0'}}>ترتیب چراغ‌ها را حفظ کن.</p></div></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:7}}>{[0,1,2,3].map(x=><button key={x} disabled={!run} onClick={()=>tap(x)} style={{height:72,borderRadius:14,border:'1px solid var(--border)',background:active===x?'#58d8ff':'#141922',color:active===x?'#051014':'white'}}>{'ABCD'[x]}</button>)}</div><button className="btn btn-primary" style={{width:'100%',marginTop:8}} onClick={start}>شروع</button></div>}

export default function SectorPetPage(){
 const ctx=useAppContext(),user=ctx.tgUser
 const [data,setData]=useState(null),[meta,setMeta]=useState(null),[tab,setTab]=useState('home'),[busy,setBusy]=useState(''),[preview,setPreview]=useState(null),[ownedOnly,setOwnedOnly]=useState(false),[category,setCategory]=useState('همه'),[msg,setMsg]=useState(''),[chat,setChat]=useState([]),[target,setTarget]=useState(''),[leaders,setLeaders]=useState([]),[seasonBoard,setSeasonBoard]=useState([]),[newName,setNewName]=useState(''),[reaction,setReaction]=useState(''),[eventFx,setEventFx]=useState(null),[soundEnabled,setSoundEnabled]=useState(()=>{try{return localStorage.getItem('sector-sound')!=='off'}catch(_){return true}})
 const reactionTimer=useRef(null),fxTimer=useRef(null)
 const metaLoad=()=>user&&ctx.apiCall('getSectorMeta',user.id).then(r=>r?.data&&setMeta(r.data))
 const load=()=>{if(!user)return;ctx.apiCall('getSectorPet',user.id).then(r=>r?.data&&setData(r.data));metaLoad()}
 useEffect(load,[user,ctx.apiCall])
 useEffect(()=>()=>{if(reactionTimer.current)clearTimeout(reactionTimer.current);if(fxTimer.current)clearTimeout(fxTimer.current)},[])
 const burst=(kind,label)=>{setEventFx({kind,label});if(fxTimer.current)clearTimeout(fxTimer.current);fxTimer.current=setTimeout(()=>setEventFx(null),1200)}
 const result=(d,reload=true,tone='success')=>{if(!d||d.status!=='success'){feedback(ctx.tg,'error',soundEnabled);ctx.showToast(d?.message||'عملیات انجام نشد','error');return false}feedback(ctx.tg,tone,soundEnabled);if(d.pet)setData(v=>({...v,pet:d.pet,shop:d.shop||v?.shop,daily:d.daily||v?.daily}));if(d.coins!==undefined)ctx.setDbUser(v=>({...v,coins:Number(d.coins)}));ctx.showToast(d.message||'انجام شد','success');if(reload)load();return true}
 const call=(name,args=[],key=name,after,tone='success')=>{if(busy)return;feedback(ctx.tg,'tap',soundEnabled);setBusy(key);ctx.apiCall(name,user.id,...args).then(r=>{const ok=result(r?.data,true,tone);if(ok&&after)after(r.data);setBusy('')}).catch(()=>{feedback(ctx.tg,'error',soundEnabled);ctx.showToast('ارتباط با هسته سکتور برقرار نشد','error');setBusy('')})}
 const action=id=>call('sectorPetAction',[id],id,()=>{setReaction(id);if(reactionTimer.current)clearTimeout(reactionTimer.current);reactionTimer.current=setTimeout(()=>setReaction(''),1500)})
 const buy=x=>call('buySectorShopItem',[x.id],'buy',()=>{setPreview(null);burst('purchase','خرید با موفقیت ثبت شد')},'buy')
 const equip=x=>call('equipSectorShopItem',[x.id],'equip',()=>{setPreview(null);burst('equip','تجهیز روی سکتور فعال شد')},'equip')
 const unequip=x=>call('unequipSectorSlot',[x.slot],'unequip',()=>setPreview(null))
 const sell=x=>call('sellSectorShopItem',[x.id],'sell',()=>setPreview(null))
 const game=(k,s)=>call('finishSectorGame',[k,s],'game')
 const rename=()=>newName.trim()&&call('renameSectorPet',[newName.trim()],'rename',()=>setNewName(''))
 const social=a=>target.trim()?call('sectorSocial',[a,target.trim()],'social'):ctx.showToast('کاربر مقصد را وارد کن','error')
 const claim=(kind,key)=>call('claimSectorReward',[kind,key],'claim',()=>{metaLoad();burst('reward','پاداش دریافت شد')})
 const boss=()=>call('attackSectorBoss',[],'boss',metaLoad)
 const story=()=>call('advanceSectorStoryV2',[],'story',metaLoad)
 const evolution=p=>call('chooseSectorEvolutionV2',[p],'evolution',()=>{metaLoad();burst('evolution','تکامل جدید فعال شد')},'evolution')
 const previous=()=>call('claimPreviousSectorSeason',[],'seasonreward',metaLoad)
 function talk(){const text=msg.trim();if(!text||busy)return;setMsg('');setChat(v=>[...v,{role:'user',text}]);setBusy('talk');ctx.apiCall('talkSectorPet',user.id,text).then(r=>{if(r?.data?.status==='success'){setChat(v=>[...v,{role:'pet',text:r.data.response}]);if(r.data.pet)setData(v=>({...v,pet:r.data.pet}));metaLoad()}else{setChat(v=>[...v,{role:'system',text:'هسته گفتگو پاسخ نداد.'}]);ctx.showToast(r?.error||r?.data?.message||'پاسخی دریافت نشد','error')}setBusy('')}).catch(()=>{setChat(v=>[...v,{role:'system',text:'هسته گفتگو موقتاً در دسترس نیست.'}]);setBusy('')})}
 function toggleSound(){setSoundEnabled(v=>{const next=!v;try{localStorage.setItem('sector-sound',next?'on':'off')}catch(_){}feedback(ctx.tg,'tap',next);return next})}
 function sharePet(){const text=`${pet.name||'سکتور کوچولو'} · سطح ${pet.level||1} · ${pet.visual_stage?.title||'Scrap Unit'}\nسکتور خودت را در @iSectorlandbot بساز.`;feedback(ctx.tg,'tap',soundEnabled);if(navigator.share)navigator.share({title:'سکتور کوچولو',text}).catch(()=>{});else navigator.clipboard?.writeText(text).then(()=>ctx.showToast('کارت سکتور کپی شد','success'))}
 if(!data)return <SectorPetSkeleton/>
 const pet=data.pet||{},shop=data.shop||[],cats=['همه',...new Set(shop.map(x=>x.category).filter(Boolean))],items=shop.filter(x=>(!ownedOnly||x.owned)&&(category==='همه'||x.category===category)),mem=data.memories||[]
 const moodId=String(pet.mood?.id||pet.mood?.key||'happy'),emotionKind=moodId.includes('sad')?'sad':moodId.includes('angry')?'angry':moodId.includes('sleep')?'sleepy':moodId.includes('love')?'love':Number(pet.energy||100)<25?'low_energy':Number(pet.hunger||100)<25?'hungry':Number(pet.cleanliness||100)<25?'dirty':'happy'
 return <div className="page fade-up" style={{paddingBottom:28}}>
  {eventFx?<div className={'sector-event-fx sector-event-fx--'+eventFx.kind} role="status"><SectorIcon name={eventFx.kind==='purchase'?'buy':eventFx.kind==='equip'?'equip':eventFx.kind==='evolution'?'growth':'gift'} size={34}/><b>{eventFx.label}</b></div>:null}
  <div className="glass" style={{padding:12,position:'relative'}}><button className="sector-sound-toggle" onClick={toggleSound} aria-label={soundEnabled?'قطع صدای سکتور':'فعال کردن صدای سکتور'}><SectorIcon name={soundEnabled?'sound':'mute'} size={18}/></button><SectorAvatar pet={pet} previewItem={preview}/>{reaction&&<div style={{position:'absolute',inset:8,display:'grid',placeItems:'center',pointerEvents:'none',background:'rgba(5,8,14,.72)',borderRadius:18,backdropFilter:'blur(4px)'}}><ActionArt action={reaction} large/></div>}<div style={{display:'flex',justifyContent:'space-between',marginTop:8}}><div><b style={{fontSize:19}}>{pet.name}</b><div style={{fontSize:9,color:'var(--muted)'}}>Lv.{pet.level} • {pet.mood?.title||'آرام'}</div></div><b className="sector-coin"><SectorIcon name="coin" size={15}/>{Number(ctx.dbUser.coins||0).toLocaleString('fa-IR')}</b></div></div>
  <div className="glass sector-tabs">{TABS.map(x=><button key={x[0]} onClick={()=>{feedback(ctx.tg,'tap',soundEnabled);setTab(x[0])}} className={tab===x[0]?'active':''}><SectorIcon name={x[0]} size={17}/><span>{x[1]}</span></button>)}</div>
  {tab==='home'&&<><Stage stage={pet.visual_stage}/><div className="glass" style={{padding:13,marginTop:8}}>{STATS.slice(0,5).map(x=><Bar key={x[0]} icon={x[0]} label={x[1]} value={pet[x[0]]}/>)}</div><div className="glass" style={{padding:12,marginTop:8}}><div style={{display:'flex',alignItems:'center',gap:8}}><StickerArt kind="mission" compact/><b>ماموریت امروز</b></div>{(data.daily?.goals||[]).map(g=><div key={g.id} style={{display:'flex',justifyContent:'space-between',fontSize:9,padding:'6px 0'}}><span>{g.title}</span><b>{g.complete?'کامل':g.progress+'/'+g.target}</b></div>)}</div><div className="glass" style={{padding:12,marginTop:8}}><b>نام سکتور</b><div style={{display:'flex',gap:6,marginTop:7}}><input value={newName} onChange={e=>setNewName(e.target.value)} maxLength={20} placeholder={pet.name} style={{flex:1,minWidth:0}}/><button className="btn" onClick={rename}>ثبت</button></div></div><SectorShareCard pet={pet} onShare={sharePet}/></>}
  {tab==='care'&&<><div className="glass" style={{padding:13}}>{STATS.map(x=><Bar key={x[0]} icon={x[0]} label={x[1]} value={pet[x[0]]}/>)}</div><div className="sector-action-grid">{Object.entries(CARE).map(([id,label])=>{const def=(data.actions||[]).find(x=>x.id===id)||{};return <button className="glass sector-action-card" key={id} disabled={!!busy} onClick={()=>action(id)}><ActionArt action={id}/><span className="sector-action-card__title"><SectorIcon name={id} size={16}/><b>{busy===id?'در حال اجرا…':label}</b></span><small>{Number(def.cost||0)} سکه</small></button>})}</div></>}
  {tab==='shop'&&<><div className="glass" style={{padding:11}}><SectorAvatar pet={pet} previewItem={preview} compact/><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:8,marginTop:6}}><div><b>{preview?.title||'پیش‌نمایش زنده'}</b><div style={{fontSize:8,color:'var(--muted)'}}>{preview?'قبل از خرید روی بدن سکتور نمایش داده شده.':'یک آیتم را لمس کن تا روی سکتورت ببینی.'}</div></div>{preview&&<button className="btn" onClick={()=>setPreview(null)}>لغو</button>}</div></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:5,margin:'8px 0'}}><button className="btn btn-primary" style={{opacity:ownedOnly?.65:1}} onClick={()=>setOwnedOnly(false)}><SectorIcon name="shop" size={16}/> فروشگاه</button><button className="btn btn-primary" style={{opacity:ownedOnly?1:.65}} onClick={()=>setOwnedOnly(true)}><SectorIcon name="equip" size={16}/> دارایی‌های من</button></div><div style={{display:'flex',gap:5,overflowX:'auto'}}>{cats.map(c=><button className="btn" key={c} onClick={()=>setCategory(c)} style={{opacity:category===c?1:.6}}>{c}</button>)}</div><div className="sector-shop-grid">{items.map(x=><div className="glass sector-shop-card" key={x.id} onClick={()=>!x.locked&&setPreview(x)} style={{opacity:x.locked?.45:1}}><ShopItemArt item={x} size={104}/><b style={{display:'block',marginTop:2}}>{x.title}</b><div style={{fontSize:8,color:'var(--muted)'}}>{x.rarity} • Lv.{x.min_level}</div><div className="sector-shop-card__price"><SectorIcon name="coin" size={13}/>{x.owned?(x.equipped?'تجهیز شده':'خریده شده'):x.cost}</div><div style={{display:'grid',gap:5}}><button className="btn" disabled={x.locked||!!busy} onClick={e=>{e.stopPropagation();x.owned?(x.equipped?unequip(x):equip(x)):buy(x)}}><SectorIcon name={x.locked?'lock':x.owned?'equip':'buy'} size={15}/>{x.locked?'قفل':x.owned?(x.equipped?'برداشتن':'تجهیز'):'خرید'}</button>{x.owned&&!x.equipped&&<button className="btn" disabled={Number(pet.level)<5||!!busy} onClick={e=>{e.stopPropagation();sell(x)}}>فروش ۵۰٪</button>}</div></div>)}{items.length===0&&<Empty>در این بخش آیتمی وجود ندارد.</Empty>}</div></>}
  {tab==='growth'&&<><Stage stage={pet.visual_stage}/><div className="glass" style={{padding:12,marginTop:8}}><div style={{display:'flex',alignItems:'center',gap:8}}><StickerArt kind="level" compact/><div><b>Unlockها</b><div style={{fontSize:8,color:'var(--muted)'}}>با رشد سکتور قابلیت و تجهیزات تازه باز می‌شوند.</div></div></div>{(meta?.unlocks||[]).map(u=><div key={u.level} style={{display:'flex',justifyContent:'space-between',fontSize:9,padding:'5px 0',opacity:u.unlocked?1:.4}}><span>{u.title}</span><b>Lv.{u.level}</b></div>)}</div><div className="glass" style={{padding:12,marginTop:8}}><b>مسیر تخصص</b><div style={{marginTop:8}}><StoryPathArt path={pet.evolution_path||'awakening'}/></div>{pet.evolution_path_info?<p>{pet.evolution_path_info.title} — {pet.evolution_path_info.perk}</p>:<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:5,marginTop:7}}>{Object.entries(data.evolution_paths||{}).map(([k,p])=><button className="btn" key={k} disabled={Number(pet.level)<Number(p.level)||!!busy} onClick={()=>evolution(k)}>{p.icon} {p.title}</button>)}</div>}<button className="btn" style={{width:'100%',marginTop:8}} onClick={story}>ادامه داستان — فصل {pet.story_chapter||1}</button></div></>}
  {tab==='season'&&<SectorLongGame meta={meta} busy={busy} onAttack={boss} onClaim={claim} onStory={story} onRefresh={metaLoad} onClaimPreviousSeason={previous} seasonBoard={seasonBoard} onSeasonBoard={()=>ctx.apiCall('getSectorSeasonLeaderboard').then(r=>r?.data&&setSeasonBoard(r.data))}/>} 
  {tab==='games'&&<><MemoryGame done={game}/><button className="btn btn-gold" style={{width:'100%',marginTop:8}} onClick={()=>ctx.navigate('games')}>آرکید کامل</button></>}
  {tab==='social'&&<><div className="glass" style={{padding:12}}><SectorFeatureArt kind="bond"/><div style={{display:'flex',alignItems:'center',gap:8,marginTop:8}}><StickerArt kind="love" compact/><div><b>تعامل و Bond</b><div style={{fontSize:8,color:'var(--muted)'}}>تعامل واقعی با سکتورهای دیگر پیوند شما را قوی‌تر می‌کند.</div></div></div><input value={target} onChange={e=>setTarget(e.target.value)} placeholder="@username" style={{width:'100%',boxSizing:'border-box',margin:'8px 0'}}/><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:5}}>{[['visit','ملاقات'],['gift','هدیه'],['battle','دوئل']].map(x=><button className="btn" key={x[0]} onClick={()=>social(x[0])}><SectorIcon name={x[0]} size={15}/>{x[1]}</button>)}</div></div><button className="btn" style={{width:'100%',marginTop:8}} onClick={()=>ctx.apiCall('getSectorLeaderboard').then(r=>r?.data&&setLeaders(r.data))}>رتبه‌بندی</button>{leaders.length>0&&<div className="glass" style={{padding:10,marginTop:7}}>{leaders.slice(0,10).map(x=><div key={x.rank} style={{display:'flex',justifyContent:'space-between',fontSize:9,padding:'5px 0'}}><span>{x.rank}. {x.name}</span><b>Lv.{x.level}</b></div>)}</div>}</>}
  {tab==='memories'&&<div className="glass" style={{padding:12}}><SectorFeatureArt kind={mem.length?'archive':'memory'}/><b style={{display:'block',marginTop:9}}>حافظه سکتور</b>{mem.length?mem.map((m,i)=><div key={m.id||i} style={{borderBottom:'1px solid var(--border)',padding:'8px 0'}}><b style={{fontSize:10}}>{m.title}</b><div style={{fontSize:9,color:'var(--muted)'}}>{m.detail}</div></div>):<Empty>هنوز خاطره معناداری ثبت نشده.</Empty>}</div>}
  {tab==='talk'&&<div className="glass" style={{padding:12,minHeight:390,display:'flex',flexDirection:'column'}}><SectorFeatureArt kind={emotionKind} compact/><div style={{display:'flex',alignItems:'center',gap:8,marginTop:8}}><StickerArt kind="love" compact/><div><b>گفت‌وگو با {pet.name}</b><div style={{fontSize:8,color:'var(--muted)'}}>Mood، مرحله رشد و خاطرات قبلی روی جواب‌ها اثر می‌گذارند.</div></div></div><div style={{flex:1,overflowY:'auto'}}>{chat.length?chat.map((m,i)=><div key={i} style={{margin:'7px 0',padding:9,borderRadius:12,background:m.role==='user'?'rgba(70,100,150,.25)':m.role==='system'?'rgba(150,70,70,.18)':'rgba(70,120,90,.22)',fontSize:10}}>{m.text}</div>):<Empty>همین‌جا پیام بده؛ لازم نیست از Mini App خارج شوی.</Empty>}</div><div style={{display:'flex',gap:5}}><input value={msg} onChange={e=>setMsg(e.target.value)} onKeyDown={e=>e.key==='Enter'&&talk()} maxLength={700} style={{flex:1,minWidth:0}}/><button className="btn btn-primary" disabled={busy==='talk'} onClick={talk}>{busy==='talk'?'...':<><SectorIcon name="send" size={16}/>ارسال</>}</button></div></div>}
 </div>
}
