import {useEffect,useRef,useState} from 'react'
import {useAppContext} from '../App'
import SectorAvatar from '../components/sector/SectorAvatar'
import SectorLongGame from '../components/sector/SectorLongGame'
import {ActionArt,ShopItemArt,StickerArt} from '../components/sector/SectorVisuals'

const CARE={charge:['PWR','شارژ انرژی'],play:['PLY','بازی'],train:['TRN','تمرین'],learn:['LRN','یادگیری'],repair:['FIX','تعمیر'],feed:['FED','غذا دادن'],clean:['CLN','تمیزکاری'],sleep:['RST','استراحت']}
const STATS=[['energy','انرژی'],['happiness','شادی'],['hunger','سیری'],['cleanliness','نظافت'],['health','سلامت'],['knowledge','دانش']]
const TABS=[['home','خانه'],['care','مراقبت'],['shop','فروشگاه'],['growth','رشد'],['season','فصل'],['games','بازی'],['social','اجتماع'],['memories','خاطرات'],['talk','گفتگو']]
function Bar({label,value,max=100}){const n=Math.max(0,Math.min(100,Number(value||0)/Math.max(1,max)*100));return <div style={{margin:'7px 0'}}><div style={{display:'flex',justifyContent:'space-between',fontSize:9}}><span>{label}</span><b>{Math.round(Number(value||0))}</b></div><div className="progress-bar"><div className="progress-fill" style={{width:n+'%'}}/></div></div>}
function Stage({stage}){const ids=['scrap','patched','core','advanced','elite','mythic'],i=Math.max(0,ids.indexOf(stage?.id));return <div className="glass" style={{padding:12}}><div style={{display:'flex',justifyContent:'space-between'}}><b>{stage?.title||'Scrap Unit'}</b><span style={{fontSize:9,color:stage?.accent}}>{stage?.condition||'فرسوده'}</span></div><div style={{display:'grid',gridTemplateColumns:'repeat(6,1fr)',gap:4,marginTop:10}}>{ids.map((x,n)=><div key={x} style={{height:5,borderRadius:5,background:n<=i?'#7486ff':'rgba(255,255,255,.08)'}}/>)}</div></div>}
function Empty({children}){return <div style={{padding:20,textAlign:'center',fontSize:10,color:'var(--muted)'}}>{children}</div>}
function MemoryGame({done}){const [seq,setSeq]=useState([]),[input,setInput]=useState([]),[active,setActive]=useState(-1),[run,setRun]=useState(false),timers=useRef([]);function clear(){timers.current.forEach(clearTimeout);timers.current=[]}useEffect(()=>clear,[]);function flash(s){clear();setRun(false);setInput([]);s.forEach((x,i)=>{timers.current.push(setTimeout(()=>setActive(x),300+i*550));timers.current.push(setTimeout(()=>setActive(-1),610+i*550))});timers.current.push(setTimeout(()=>setRun(true),350+s.length*550))}function start(){const s=[0,1,2].map(()=>Math.floor(Math.random()*4));setSeq(s);flash(s)}function tap(x){if(!run)return;const n=[...input,x];setInput(n);if(seq[n.length-1]!==x){setRun(false);done('circuit',Math.max(10,(seq.length-3)*20));return}if(n.length===seq.length){if(seq.length>=8){setRun(false);done('circuit',100)}else{const s=[...seq,Math.floor(Math.random()*4)];setSeq(s);setTimeout(()=>flash(s),450)}}}return <div className="glass" style={{padding:14}}><div style={{display:'flex',alignItems:'center',gap:8}}><StickerArt kind="mission" compact/><div><b>مدار حافظه</b><p style={{fontSize:9,color:'var(--muted)',margin:'4px 0'}}>ترتیب چراغ‌ها را حفظ کن.</p></div></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:7}}>{[0,1,2,3].map(x=><button key={x} disabled={!run} onClick={()=>tap(x)} style={{height:72,borderRadius:14,border:'1px solid var(--border)',background:active===x?'#58d8ff':'#141922',color:active===x?'#051014':'white'}}>{'ABCD'[x]}</button>)}</div><button className="btn btn-primary" style={{width:'100%',marginTop:8}} onClick={start}>شروع</button></div>}

export default function SectorPetPage(){
 const ctx=useAppContext(),user=ctx.tgUser
 const [data,setData]=useState(null),[meta,setMeta]=useState(null),[tab,setTab]=useState('home'),[busy,setBusy]=useState(''),[preview,setPreview]=useState(null),[ownedOnly,setOwnedOnly]=useState(false),[category,setCategory]=useState('همه'),[msg,setMsg]=useState(''),[chat,setChat]=useState([]),[target,setTarget]=useState(''),[leaders,setLeaders]=useState([]),[seasonBoard,setSeasonBoard]=useState([]),[newName,setNewName]=useState(''),[reaction,setReaction]=useState('')
 const reactionTimer=useRef(null)
 const metaLoad=()=>user&&ctx.apiCall('getSectorMeta',user.id).then(r=>r?.data&&setMeta(r.data))
 const load=()=>{if(!user)return;ctx.apiCall('getSectorPet',user.id).then(r=>r?.data&&setData(r.data));metaLoad()}
 useEffect(load,[user,ctx.apiCall])
 useEffect(()=>()=>reactionTimer.current&&clearTimeout(reactionTimer.current),[])
 const result=(d,reload=true)=>{if(!d||d.status!=='success'){ctx.showToast(d?.message||'عملیات انجام نشد','error');return false}if(d.pet)setData(v=>({...v,pet:d.pet,shop:d.shop||v?.shop,daily:d.daily||v?.daily}));if(d.coins!==undefined)ctx.setDbUser(v=>({...v,coins:Number(d.coins)}));ctx.showToast(d.message||'انجام شد','success');if(reload)load();return true}
 const call=(name,args=[],key=name,after)=>{if(busy)return;setBusy(key);ctx.apiCall(name,user.id,...args).then(r=>{const ok=result(r?.data);if(ok&&after)after(r.data);setBusy('')}).catch(()=>{ctx.showToast('ارتباط با هسته سکتور برقرار نشد','error');setBusy('')})}
 const action=id=>call('sectorPetAction',[id],id,()=>{setReaction(id);if(reactionTimer.current)clearTimeout(reactionTimer.current);reactionTimer.current=setTimeout(()=>setReaction(''),1500)})
 const buy=x=>call('buySectorShopItem',[x.id],'buy',()=>setPreview(null))
 const equip=x=>call('equipSectorShopItem',[x.id],'equip',()=>setPreview(null))
 const unequip=x=>call('unequipSectorSlot',[x.slot],'unequip',()=>setPreview(null))
 const sell=x=>call('sellSectorShopItem',[x.id],'sell',()=>setPreview(null))
 const game=(k,s)=>call('finishSectorGame',[k,s],'game')
 const rename=()=>newName.trim()&&call('renameSectorPet',[newName.trim()],'rename',()=>setNewName(''))
 const social=a=>target.trim()?call('sectorSocial',[a,target.trim()],'social'):ctx.showToast('کاربر مقصد را وارد کن','error')
 const claim=(kind,key)=>call('claimSectorReward',[kind,key],'claim',metaLoad)
 const boss=()=>call('attackSectorBoss',[],'boss',metaLoad)
 const story=()=>call('advanceSectorStoryV2',[],'story',metaLoad)
 const evolution=p=>call('chooseSectorEvolutionV2',[p],'evolution',metaLoad)
 const previous=()=>call('claimPreviousSectorSeason',[],'seasonreward',metaLoad)
 function talk(){const text=msg.trim();if(!text||busy)return;setMsg('');setChat(v=>[...v,{role:'user',text}]);setBusy('talk');ctx.apiCall('talkSectorPet',user.id,text).then(r=>{if(r?.data?.status==='success'){setChat(v=>[...v,{role:'pet',text:r.data.response}]);if(r.data.pet)setData(v=>({...v,pet:r.data.pet}));metaLoad()}else{setChat(v=>[...v,{role:'system',text:'هسته گفتگو پاسخ نداد.'}]);ctx.showToast(r?.error||r?.data?.message||'پاسخی دریافت نشد','error')}setBusy('')}).catch(()=>{setChat(v=>[...v,{role:'system',text:'هسته گفتگو موقتاً در دسترس نیست.'}]);setBusy('')})}
 if(!data)return <div className="page"><div className="glass" style={{padding:28,textAlign:'center'}}>در حال اتصال به هسته سکتور…</div></div>
 const pet=data.pet||{},shop=data.shop||[],cats=['همه',...new Set(shop.map(x=>x.category).filter(Boolean))],items=shop.filter(x=>(!ownedOnly||x.owned)&&(category==='همه'||x.category===category)),mem=data.memories||[]
 return <div className="page fade-up" style={{paddingBottom:28}}>
  <div className="glass" style={{padding:12,position:'relative'}}><SectorAvatar pet={pet} previewItem={preview}/>{reaction&&<div style={{position:'absolute',inset:8,display:'grid',placeItems:'center',pointerEvents:'none',background:'rgba(5,8,14,.72)',borderRadius:18,backdropFilter:'blur(4px)'}}><ActionArt action={reaction} large/></div>}<div style={{display:'flex',justifyContent:'space-between',marginTop:8}}><div><b style={{fontSize:19}}>{pet.name}</b><div style={{fontSize:9,color:'var(--muted)'}}>Lv.{pet.level} • {pet.mood?.title||'آرام'}</div></div><b>{Number(ctx.dbUser.coins||0).toLocaleString('fa-IR')} سکه</b></div></div>
  <div className="glass" style={{display:'flex',gap:4,padding:5,margin:'9px 0',overflowX:'auto',position:'sticky',top:4,zIndex:5}}>{TABS.map(x=><button key={x[0]} onClick={()=>setTab(x[0])} style={{flex:'0 0 auto',border:0,borderRadius:9,padding:'8px 10px',background:tab===x[0]?'#394a70':'transparent',color:'white'}}>{x[1]}</button>)}</div>
  {tab==='home'&&<><Stage stage={pet.visual_stage}/><div className="glass" style={{padding:13,marginTop:8}}>{STATS.slice(0,5).map(x=><Bar key={x[0]} label={x[1]} value={pet[x[0]]}/>)}</div><div className="glass" style={{padding:12,marginTop:8}}><div style={{display:'flex',alignItems:'center',gap:8}}><StickerArt kind="mission" compact/><b>ماموریت امروز</b></div>{(data.daily?.goals||[]).map(g=><div key={g.id} style={{display:'flex',justifyContent:'space-between',fontSize:9,padding:'6px 0'}}><span>{g.title}</span><b>{g.complete?'کامل':g.progress+'/'+g.target}</b></div>)}</div><div className="glass" style={{padding:12,marginTop:8}}><b>نام سکتور</b><div style={{display:'flex',gap:6,marginTop:7}}><input value={newName} onChange={e=>setNewName(e.target.value)} maxLength={20} placeholder={pet.name} style={{flex:1,minWidth:0}}/><button className="btn" onClick={rename}>ثبت</button></div></div></>}
  {tab==='care'&&<><div className="glass" style={{padding:13}}>{STATS.map(x=><Bar key={x[0]} label={x[1]} value={pet[x[0]]}/>)}</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:7,marginTop:8}}>{Object.entries(CARE).map(([id,a])=>{const def=(data.actions||[]).find(x=>x.id===id)||{};return <button className="glass" key={id} disabled={!!busy} onClick={()=>action(id)} style={{padding:10,color:'inherit',textAlign:'center',overflow:'hidden'}}><ActionArt action={id}/><small style={{color:'var(--muted)'}}>{busy===id?'RUN':a[0]}</small><b style={{display:'block',marginTop:2}}>{a[1]}</b><small>{Number(def.cost||0)} سکه</small></button>})}</div></>}
  {tab==='shop'&&<><div className="glass" style={{padding:11}}><SectorAvatar pet={pet} previewItem={preview} compact/><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:8,marginTop:6}}><div><b>{preview?.title||'پیش‌نمایش زنده'}</b><div style={{fontSize:8,color:'var(--muted)'}}>{preview?'قبل از خرید روی بدن سکتور نمایش داده شده.':'یک آیتم را لمس کن تا روی سکتورت ببینی.'}</div></div>{preview&&<button className="btn" onClick={()=>setPreview(null)}>لغو</button>}</div></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:5,margin:'8px 0'}}><button className="btn btn-primary" style={{opacity:ownedOnly?.65:1}} onClick={()=>setOwnedOnly(false)}>فروشگاه</button><button className="btn btn-primary" style={{opacity:ownedOnly?1:.65}} onClick={()=>setOwnedOnly(true)}>دارایی‌های من</button></div><div style={{display:'flex',gap:5,overflowX:'auto'}}>{cats.map(c=><button className="btn" key={c} onClick={()=>setCategory(c)} style={{opacity:category===c?1:.6}}>{c}</button>)}</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:7,marginTop:8}}>{items.map(x=><div className="glass" key={x.id} onClick={()=>!x.locked&&setPreview(x)} style={{padding:9,opacity:x.locked?.45:1,textAlign:'center'}}><ShopItemArt item={x} size={104}/><b style={{display:'block',marginTop:2}}>{x.title}</b><div style={{fontSize:8,color:'var(--muted)'}}>{x.rarity} • Lv.{x.min_level}</div><div style={{fontSize:9,margin:'6px 0'}}>{x.owned?(x.equipped?'تجهیز شده':'خریده شده'):x.cost+' سکه'}</div><div style={{display:'grid',gap:5}}><button className="btn" disabled={x.locked||!!busy} onClick={e=>{e.stopPropagation();x.owned?(x.equipped?unequip(x):equip(x)):buy(x)}}>{x.locked?'قفل':x.owned?(x.equipped?'برداشتن':'تجهیز'):'خرید'}</button>{x.owned&&!x.equipped&&<button className="btn" disabled={Number(pet.level)<5||!!busy} onClick={e=>{e.stopPropagation();sell(x)}}>فروش ۵۰٪</button>}</div></div>)}{items.length===0&&<Empty>در این بخش آیتمی وجود ندارد.</Empty>}</div></>}
  {tab==='growth'&&<><Stage stage={pet.visual_stage}/><div className="glass" style={{padding:12,marginTop:8}}><div style={{display:'flex',alignItems:'center',gap:8}}><StickerArt kind="level" compact/><div><b>Unlockها</b><div style={{fontSize:8,color:'var(--muted)'}}>با رشد سکتور قابلیت و تجهیزات تازه باز می‌شوند.</div></div></div>{(meta?.unlocks||[]).map(u=><div key={u.level} style={{display:'flex',justifyContent:'space-between',fontSize:9,padding:'5px 0',opacity:u.unlocked?1:.4}}><span>{u.title}</span><b>Lv.{u.level}</b></div>)}</div><div className="glass" style={{padding:12,marginTop:8}}><b>مسیر تخصص</b>{pet.evolution_path_info?<p>{pet.evolution_path_info.title} — {pet.evolution_path_info.perk}</p>:<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:5,marginTop:7}}>{Object.entries(data.evolution_paths||{}).map(([k,p])=><button className="btn" key={k} disabled={Number(pet.level)<Number(p.level)||!!busy} onClick={()=>evolution(k)}>{p.icon} {p.title}</button>)}</div>}<button className="btn" style={{width:'100%',marginTop:8}} onClick={story}>ادامه داستان — فصل {pet.story_chapter||1}</button></div></>}
  {tab==='season'&&<SectorLongGame meta={meta} busy={busy} onAttack={boss} onClaim={claim} onStory={story} onRefresh={metaLoad} onClaimPreviousSeason={previous} seasonBoard={seasonBoard} onSeasonBoard={()=>ctx.apiCall('getSectorSeasonLeaderboard').then(r=>r?.data&&setSeasonBoard(r.data))}/>} 
  {tab==='games'&&<><MemoryGame done={game}/><button className="btn btn-gold" style={{width:'100%',marginTop:8}} onClick={()=>ctx.navigate('games')}>آرکید کامل</button></>}
  {tab==='social'&&<><div className="glass" style={{padding:12}}><div style={{display:'flex',alignItems:'center',gap:8}}><StickerArt kind="love" compact/><div><b>تعامل و Bond</b><div style={{fontSize:8,color:'var(--muted)'}}>تعامل واقعی با سکتورهای دیگر پیوند شما را قوی‌تر می‌کند.</div></div></div><input value={target} onChange={e=>setTarget(e.target.value)} placeholder="@username" style={{width:'100%',boxSizing:'border-box',margin:'8px 0'}}/><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:5}}>{[['visit','ملاقات'],['gift','هدیه'],['battle','دوئل']].map(x=><button className="btn" key={x[0]} onClick={()=>social(x[0])}>{x[1]}</button>)}</div></div><button className="btn" style={{width:'100%',marginTop:8}} onClick={()=>ctx.apiCall('getSectorLeaderboard').then(r=>r?.data&&setLeaders(r.data))}>رتبه‌بندی</button>{leaders.length>0&&<div className="glass" style={{padding:10,marginTop:7}}>{leaders.slice(0,10).map(x=><div key={x.rank} style={{display:'flex',justifyContent:'space-between',fontSize:9,padding:'5px 0'}}><span>{x.rank}. {x.name}</span><b>Lv.{x.level}</b></div>)}</div>}</>}
  {tab==='memories'&&<div className="glass" style={{padding:12}}><b>حافظه سکتور</b>{mem.length?mem.map((m,i)=><div key={m.id||i} style={{borderBottom:'1px solid var(--border)',padding:'8px 0'}}><b style={{fontSize:10}}>{m.title}</b><div style={{fontSize:9,color:'var(--muted)'}}>{m.detail}</div></div>):<Empty>هنوز خاطره معناداری ثبت نشده.</Empty>}</div>}
  {tab==='talk'&&<div className="glass" style={{padding:12,minHeight:390,display:'flex',flexDirection:'column'}}><div style={{display:'flex',alignItems:'center',gap:8}}><StickerArt kind="love" compact/><div><b>گفت‌وگو با {pet.name}</b><div style={{fontSize:8,color:'var(--muted)'}}>Mood، مرحله رشد و خاطرات قبلی روی جواب‌ها اثر می‌گذارند.</div></div></div><div style={{flex:1,overflowY:'auto'}}>{chat.length?chat.map((m,i)=><div key={i} style={{margin:'7px 0',padding:9,borderRadius:12,background:m.role==='user'?'rgba(70,100,150,.25)':m.role==='system'?'rgba(150,70,70,.18)':'rgba(70,120,90,.22)',fontSize:10}}>{m.text}</div>):<Empty>همین‌جا پیام بده؛ لازم نیست از Mini App خارج شوی.</Empty>}</div><div style={{display:'flex',gap:5}}><input value={msg} onChange={e=>setMsg(e.target.value)} onKeyDown={e=>e.key==='Enter'&&talk()} maxLength={700} style={{flex:1,minWidth:0}}/><button className="btn btn-primary" disabled={busy==='talk'} onClick={talk}>{busy==='talk'?'...':'ارسال'}</button></div></div>}
 </div>
}
