import { useEffect, useMemo, useState } from 'react'
import { useAppContext } from '../App'

const ICONS={charge:'⚡',play:'🎮',train:'🏋️',learn:'🧠',repair:'🔧',feed:'🍪',clean:'🫧',sleep:'🌙'}
const STATS={energy:['⚡','انرژی'],happiness:['💙','شادی'],hunger:['🍪','سیری'],cleanliness:['🫧','نظافت'],knowledge:['🧠','دانش'],health:['❤️','سلامتی']}
const ITEMS={neon_lamp:{title:'چراغ نئونی',icon:'💡',cost:450},game_console:{title:'کنسول بازی',icon:'🕹️',cost:900},space_window:{title:'پنجره فضایی',icon:'🪐',cost:1800},ai_core:{title:'هسته هوشمند',icon:'🔮',cost:4000}}

function Meter({name,value}){var meta=STATS[name];return <div style={{marginBottom:10}}><div style={{display:'flex',justifyContent:'space-between',fontSize:11,marginBottom:5}}><span>{meta[0]} {meta[1]}</span><b>{value}%</b></div><div className="progress-bar"><div className="progress-fill" style={{width:value+'%',background:value<25?'linear-gradient(90deg,#ff5578,#ff8d54)':undefined}}/></div></div>}

function MemoryGame({finish}){var symbols=['⚡','🔧','💎','🧠'],[seq,setSeq]=useState([]),[input,setInput]=useState([]),[show,setShow]=useState(false),[playing,setPlaying]=useState(false)
  function start(){var s=Array.from({length:4},()=>symbols[Math.floor(Math.random()*symbols.length)]);setSeq(s);setInput([]);setPlaying(true);setShow(true);setTimeout(()=>setShow(false),2200)}
  function tap(x){if(!playing||show)return;var next=input.concat(x);setInput(next);if(x!==seq[next.length-1]){finish('circuit',Math.max(10,(next.length-1)*25));setPlaying(false)}else if(next.length===seq.length){finish('circuit',100);setPlaying(false)}}
  return <div className="glass" style={{padding:14}}><b>🧩 مدار حافظه</b><p style={{fontSize:10,color:'var(--muted)',lineHeight:1.8}}>ترتیب مدارها را به خاطر بسپار و تکرار کن.</p><div style={{minHeight:42,textAlign:'center',fontSize:27,letterSpacing:6}}>{show?seq.join(' '):(playing?'❔ ❔ ❔ ❔':'برای شروع آماده‌ای؟')}</div><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:7,marginTop:9}}>{symbols.map(x=><button key={x} className="btn" disabled={!playing||show} onClick={()=>tap(x)}>{x}</button>)}</div><button className="btn btn-primary" style={{width:'100%',marginTop:9}} onClick={start}>شروع مدار</button></div>}

function BatteryGame({finish}){var [left,setLeft]=useState(0),[hits,setHits]=useState(0),[running,setRunning]=useState(false)
  useEffect(()=>{if(!running)return;if(left<=0){finish('battery',Math.min(100,hits*5));setRunning(false);return}var timer=setTimeout(()=>setLeft(v=>v-1),1000);return()=>clearTimeout(timer)},[left,running])
  return <div className="glass" style={{padding:14}}><b>🔋 شارژ سریع</b><p style={{fontSize:10,color:'var(--muted)',lineHeight:1.8}}>در ۱۰ ثانیه هسته انرژی را تا می‌توانی لمس کن.</p><div style={{fontSize:12,textAlign:'center'}}>زمان: {left} • شارژ: {hits}</div><button className="btn btn-gold" disabled={!running} onClick={()=>setHits(v=>v+1)} style={{width:'100%',height:82,fontSize:35,marginTop:9}}>⚡</button><button className="btn btn-primary" disabled={running} onClick={()=>{setHits(0);setLeft(10);setRunning(true)}} style={{width:'100%',marginTop:9}}>شروع شارژ</button></div>}

export default function SectorPetPage(){
  var ctx=useAppContext(),user=ctx.tgUser,[data,setData]=useState(null),[tab,setTab]=useState('home'),[busy,setBusy]=useState(''),[newName,setNewName]=useState(''),[message,setMessage]=useState(''),[chat,setChat]=useState([])
  function load(){if(!user)return;ctx.apiCall('getSectorPet',user.id).then(r=>{if(r&&r.data)setData(r.data)})}
  useEffect(load,[user,ctx.apiCall])
  function applyResult(d){if(d&&d.status==='success'){setData(v=>({...v,pet:d.pet||v.pet,daily:d.daily||v.daily}));if(d.coins!==undefined)ctx.setDbUser(u=>({...u,coins:Number(d.coins)}));ctx.showToast(d.message,'success')}else ctx.showToast((d&&d.message)||'عملیات انجام نشد.','error')}
  function act(id){if(busy)return;setBusy(id);ctx.apiCall('sectorPetAction',user.id,id).then(r=>{applyResult(r&&r.data);setBusy('')})}
  function buy(id){if(busy)return;setBusy('buy');ctx.apiCall('buySectorRoomItem',user.id,id).then(r=>{applyResult(r&&r.data);setBusy('')})}
  function finish(game,score){if(busy)return;setBusy('game');ctx.apiCall('finishSectorGame',user.id,game,score).then(r=>{applyResult(r&&r.data);setBusy('')})}
  function rename(){var name=newName.trim();if(!name)return;setBusy('rename');ctx.apiCall('renameSectorPet',user.id,name).then(r=>{applyResult(r&&r.data);setNewName('');setBusy('')})}
  function talk(){var text=message.trim();if(!text||busy)return;setMessage('');setChat(v=>v.concat({role:'user',text}));setBusy('talk');ctx.apiCall('talkSectorPet',user.id,text).then(r=>{var d=r&&r.data;if(d&&d.status==='success')setChat(v=>v.concat({role:'pet',text:d.response}));else ctx.showToast((r&&r.error)||'سکتور جواب نداد','error');setBusy('')})}
  var tabs=useMemo(()=>[['home','🏠 خانه'],['care','💙 مراقبت'],['games','🎮 بازی'],['talk','💬 گفتگو']],[])
  if(!data)return <div className="page"><div className="glass" style={{padding:24,textAlign:'center'}}>🤖 در حال بیدار کردن سکتور...</div></div>
  var pet=data.pet,stage=pet.stage||{id:1,title:'سکتور کوچولو'},daily=data.daily||{goals:[]},mood=pet.mood||{emoji:'🤖',title:'آرام',line:'خوشحالم که برگشتی.'},owned=pet.inventory||{}
  return <div className="page fade-up">
    <div className="glass" style={{padding:15,textAlign:'center',overflow:'hidden',background:'radial-gradient(circle at 50% 10%,rgba(52,226,255,.2),transparent 48%),linear-gradient(160deg,rgba(35,22,91,.78),rgba(6,12,28,.94))'}}><div style={{fontSize:10,color:'#64efff',fontWeight:900,letterSpacing:1}}>SECTOR COMPANION</div><b style={{fontSize:21}}>{pet.name}</b><div style={{fontSize:11,color:'var(--muted)'}}>{stage.title} • سطح {pet.level} • شخصیت {pet.personality}</div><div style={{position:'relative',height:185}}><img src="/assets/sector-evolution.webp" alt="سکتور کوچولو" style={{width:'100%',maxWidth:390,position:'absolute',left:'50%',top:-32,transform:'translateX(-50%)',filter:'drop-shadow(0 15px 28px rgba(0,208,255,.3))'}}/><div style={{position:'absolute',bottom:4,left:8,right:8,padding:'8px 10px',borderRadius:14,background:'rgba(5,10,25,.78)',fontSize:11}}>{mood.emoji} <b>{mood.title}:</b> {mood.line}</div></div><div style={{display:'flex',justifyContent:'space-between',fontSize:10,color:'var(--muted)'}}><span>XP سطح</span><span>{pet.xp_in_level} / {pet.xp_next}</span></div><div className="progress-bar" style={{marginTop:6}}><div className="progress-fill" style={{width:Math.min(100,pet.xp_in_level/pet.xp_next*100)+'%'}}/></div></div>
    <div className="glass" style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:4,padding:5,margin:'10px 0 14px',position:'sticky',top:5,zIndex:5}}>{tabs.map(t=><button key={t[0]} onClick={()=>setTab(t[0])} style={{border:0,borderRadius:10,padding:'9px 2px',fontSize:10,color:'white',background:tab===t[0]?'linear-gradient(135deg,#4169ff,#8a43ff)':'transparent'}}>{t[1]}</button>)}</div>
    {tab==='home'&&<><div className="glass" style={{padding:14,display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,textAlign:'center'}}><div>🔥 <b>{pet.streak_days||0} روز</b><small style={{display:'block',color:'var(--muted)'}}>زنجیره حضور</small></div><div>📅 <b>{pet.total_care_days||0} روز</b><small style={{display:'block',color:'var(--muted)'}}>مراقبت واقعی</small></div></div><div className="sec-title">ماموریت‌های امروز</div><div className="glass" style={{padding:14}}>{(daily.goals||[]).map(g=><div key={g.id} style={{display:'flex',justifyContent:'space-between',fontSize:11,padding:'7px 0',borderBottom:'1px solid var(--border)'}}><span>{g.complete?'✅':'🔄'} {g.title}</span><b>{g.progress}/{g.target}</b></div>)}</div><div className="sec-title">اتاق {pet.name}</div><div className="glass" style={{padding:14,background:'linear-gradient(160deg,rgba(32,51,91,.8),rgba(24,13,57,.9))'}}><div style={{fontSize:44,textAlign:'center',padding:14}}>{Object.keys(owned).length?Object.keys(owned).map(k=><span key={k} style={{margin:6}}>{ITEMS[k]?.icon}</span>):'🛏️ 🤖'}</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:7}}>{Object.entries(ITEMS).map(([id,it])=><button key={id} className="btn" disabled={busy==='buy'||owned[id]} onClick={()=>buy(id)} style={{fontSize:10}}>{it.icon} {owned[id]?'خریده شد':it.title+' • '+it.cost}</button>)}</div></div></>}
    {tab==='care'&&<><div className="sec-title">وضعیت زنده</div><div className="glass" style={{padding:14}}>{Object.keys(STATS).map(k=><Meter key={k} name={k} value={Number(pet[k]||0)}/>)}</div><div className="sec-title">مراقبت و رشد</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:9}}>{data.actions.map(a=><button key={a.id} className="glass" disabled={!!busy} onClick={()=>act(a.id)} style={{padding:14,color:'inherit',border:'1px solid var(--border)'}}><div style={{fontSize:27}}>{busy===a.id?'⏳':ICONS[a.id]}</div><b style={{fontSize:11}}>{a.title}</b><div style={{fontSize:9,color:'var(--muted)'}}>{ctx.dbUser.unlimited_wallet?'رایگان':a.cost+' سکه'} • +{a.xp} XP</div></button>)}</div><div className="glass" style={{padding:14,marginTop:12}}><b>✏️ تغییر نام</b><div style={{display:'flex',gap:7,marginTop:8}}><input value={newName} maxLength={20} onChange={e=>setNewName(e.target.value)} placeholder={pet.name} style={{flex:1,minWidth:0,padding:10,borderRadius:10,border:'1px solid var(--border)',background:'var(--bg)',color:'white'}}/><button className="btn btn-primary" onClick={rename}>ثبت</button></div></div></>}
    {tab==='games'&&<div style={{display:'grid',gap:11}}><MemoryGame finish={finish}/><BatteryGame finish={finish}/><button className="btn btn-gold" onClick={()=>ctx.navigate('games')}>🎮 ورود به آرکید کامل سکتورلند</button><div className="glass" style={{padding:12,fontSize:10,color:'var(--muted)'}}>هر بازی روزانه ۵ بار جایزه می‌دهد. امتیاز به شادی، XP و مأموریت روزانه اضافه می‌شود.</div></div>}
    {tab==='talk'&&<><div className="glass" style={{padding:14}}><b>💬 گفت‌وگوی خصوصی با {pet.name}</b><p style={{fontSize:10,color:'var(--muted)'}}>حافظه و شخصیت این همراه مستقل از هوش عمومی ربات است.</p>{chat.map((m,i)=><div key={i} style={{marginTop:8,padding:'9px 11px',borderRadius:12,background:m.role==='user'?'rgba(79,123,255,.18)':'rgba(34,216,122,.12)',fontSize:12,marginRight:m.role==='user'?24:0,marginLeft:m.role==='pet'?24:0}}>{m.role==='pet'?pet.name+': ':''}{m.text}</div>)}<div style={{display:'flex',gap:7,marginTop:10}}><input value={message} maxLength={700} onKeyDown={e=>{if(e.key==='Enter')talk()}} onChange={e=>setMessage(e.target.value)} placeholder={'به '+pet.name+' بگو…'} style={{flex:1,minWidth:0,padding:10,borderRadius:10,border:'1px solid var(--border)',background:'var(--bg)',color:'white'}}/><button className="btn btn-primary" disabled={busy==='talk'} onClick={talk}>{busy==='talk'?'⏳':'ارسال'}</button></div></div><div className="glass" style={{padding:12,marginTop:10,fontSize:10,color:'var(--muted)'}}>🤝 بازی دونفره و عملیات بانکی از بخش تعامل سکتور در چت ربات هم در دسترس است.</div></>}
    <div className="glass" style={{padding:12,marginTop:14,fontSize:10,color:'var(--muted)',lineHeight:1.9}}>🧬 {stage.next_gate?'تکامل بعدی: سطح '+stage.next_gate.level+' و '+stage.next_gate.care_days+' روز مراقبت واقعی.':'سکتور به فرم نهایی رسیده است.'} رشد برای ماه‌ها طراحی شده و بازگشت روزانه از تکرار زیاد در یک روز ارزشمندتر است.</div><div style={{height:24}}/>
  </div>
}
