-- iSectorLand unified bot database (isolated namespace)
-- Shares a Supabase project with SectorLand NewsBot but never shares tables.

create table if not exists public.isectorbot_users (
  id bigint primary key,
  username text,
  first_name text not null default '',
  coins bigint not null default 0,
  bank bigint not null default 0,
  loan bigint not null default 0,
  xp bigint not null default 0,
  level integer not null default 1,
  message_count bigint not null default 0,
  last_daily_claim timestamptz,
  vip_until timestamptz,
  is_admin boolean not null default false,
  joined_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.isectorbot_groups (
  id bigint primary key,
  title text not null default '',
  lock_links boolean not null default false,
  lock_usernames boolean not null default false,
  lock_forward boolean not null default false,
  lock_photos boolean not null default false,
  lock_videos boolean not null default false,
  lock_files boolean not null default false,
  lock_stickers boolean not null default false,
  lock_gifs boolean not null default false,
  lock_voice boolean not null default false,
  lock_contacts boolean not null default false,
  welcome_enabled boolean not null default true,
  welcome_text text not null default 'خوش اومدی به گروه 🌟\nلطفاً قوانین رو رعایت کن.',
  rules text,
  rules_enabled boolean not null default true,
  antispam_enabled boolean not null default true,
  antispam_limit integer not null default 5,
  economy_enabled boolean not null default true,
  ai_enabled boolean not null default true,
  prevent_bots boolean not null default false,
  new_member_limit boolean not null default false,
  approval_mode boolean not null default false,
  activity_logging boolean not null default true,
  is_active boolean not null default true,
  joined_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.isectorbot_warnings (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.isectorbot_users(id) on delete cascade,
  group_id bigint not null references public.isectorbot_groups(id) on delete cascade,
  reason text not null default 'بدون دلیل',
  warned_by bigint not null,
  created_at timestamptz not null default now()
);

create table if not exists public.isectorbot_mutes (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.isectorbot_users(id) on delete cascade,
  group_id bigint not null references public.isectorbot_groups(id) on delete cascade,
  until_at timestamptz,
  created_at timestamptz not null default now(),
  unique(user_id, group_id)
);

create table if not exists public.isectorbot_purchases (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.isectorbot_users(id) on delete cascade,
  item_id text not null,
  amount bigint not null default 0,
  telegram_payment_charge_id text unique,
  status text not null default 'completed',
  created_at timestamptz not null default now()
);

create table if not exists public.isectorbot_orders (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.isectorbot_users(id) on delete cascade,
  item_key text not null,
  item_name text not null,
  price bigint not null default 0,
  status text not null default 'pending' check (status in ('pending','active','expired','cancelled')),
  created_at timestamptz not null default now(),
  expires_at timestamptz,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.isectorbot_referrals (
  id bigint generated by default as identity primary key,
  referrer_id bigint not null references public.isectorbot_users(id) on delete cascade,
  referred_id bigint not null references public.isectorbot_users(id) on delete cascade,
  reward bigint not null default 0,
  created_at timestamptz not null default now(),
  unique(referred_id)
);

create table if not exists public.isectorbot_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

create index if not exists isectorbot_users_coins_idx on public.isectorbot_users(coins desc);
create index if not exists isectorbot_users_activity_idx on public.isectorbot_users(message_count desc);
create index if not exists isectorbot_warnings_group_user_idx on public.isectorbot_warnings(group_id,user_id);
create index if not exists isectorbot_orders_user_idx on public.isectorbot_orders(user_id,created_at desc);
create index if not exists isectorbot_purchases_user_idx on public.isectorbot_purchases(user_id,created_at desc);

alter table public.isectorbot_users enable row level security;
alter table public.isectorbot_groups enable row level security;
alter table public.isectorbot_warnings enable row level security;
alter table public.isectorbot_mutes enable row level security;
alter table public.isectorbot_purchases enable row level security;
alter table public.isectorbot_orders enable row level security;
alter table public.isectorbot_referrals enable row level security;
alter table public.isectorbot_settings enable row level security;

revoke all on public.isectorbot_users, public.isectorbot_groups, public.isectorbot_warnings,
  public.isectorbot_mutes, public.isectorbot_purchases, public.isectorbot_orders,
  public.isectorbot_referrals, public.isectorbot_settings from anon, authenticated;
