import {useEffect,useState} from 'react'
import {ShopItemArt} from './SectorVisuals'

const SLOT_INFO={core:['هسته','انرژی و فناوری'],armor:['زره','دفاع و مقاومت'],arm:['بازوی اصلی','قدرت و سرعت'],visor:['ویزور','دقت و تحلیل'],back:['سامانه پشتی','انرژی و سرعت'],defense_module:['ماژول دفاعی','مقاومت و سپر'],tool:['ابزار تخصصی','قدرت و فناوری'],badge:['نشان ویژه','پاداش مجموعه']}
const STAT_LABELS={power:'قدرت حمله',defense:'دفاع',energy_bonus:'انرژی',accuracy:'دقت',speed:'سرعت',resistance:'مقاومت',tech:'فناوری',power_score:'Power Score'}

function Timer({seconds}){const [left,setLeft]=useState(Number(seconds||0));useEffect(()=>{setLeft(Number(seconds||0));const id=setInterval(()=>setLeft(v=>Math.max(0,v-1)),1000);return()=>clearInterval(id)},[seconds]);return <time>{[Math.floor(left/3600),Math.floor(left%3600/60),left%60].map(x=>String(x).padStart(2,'0')).join(':')}</time>}

export default function SectorRobotWorkshop({pet,shop,onCommand,onEquip,busy,compact=false}){
 const stats=pet?.equipment_stats||{},stage=pet?.visual_stage?.id||'scrap',equipped=new Map(shop.filter(x=>x.owned&&x.equipped).map(x=>[x.slot,x])),weakest=[...SLOT_INFO.keys()].map(slot=>equipped.get(slot)).filter(Boolean).sort((a,b)=>(a.effective_power+a.effective_defense)-(b.effective_power+b.effective_defense))[0]
 const identity=<header className="sector-id-card"><div className="sector-id-card__image"><img src={`/assets/sector/stages-v3/${stage}.webp`} alt={`تصویر ${pet?.name||'سکتور'}`}/><span>{pet?.mood?.emoji||'🤖'} {pet?.mood?.title||'پایدار'}</span></div><div className="sector-id-card__copy"><small>SECTOR IDENTITY</small><h2>{pet?.name||'سکتور من'}</h2><p>Lv.{pet?.level||1} · {pet?.visual_stage?.title||'Sector Unit'} · {stats.tier||'پایه'}</p><strong>{Number(stats.power_score||0).toLocaleString('fa-IR')}<i>POWER SCORE</i></strong></div></header>
 if(compact)return <section className="sector-loadout sector-loadout--compact">{identity}<div className="sector-loadout__stats">{[['power','قدرت'],['defense','دفاع'],['energy_bonus','انرژی'],['tech','فناوری']].map(([key,label])=><span key={key}><small>{label}</small><b>{stats[key]||0}</b></span>)}</div></section>
 return <section className="sector-loadout">
  {identity}
  <div className="sector-loadout__stats">{Object.entries(STAT_LABELS).map(([key,label])=><span key={key} className={key==='power_score'?'primary':''}><small>{label}</small><b>{stats[key]||0}</b></span>)}</div>
  {stats.set_bonus?<div className="sector-set-bonus"><b>پاداش {stats.set_bonus.title}</b><span>{stats.set_bonus.count} قطعه هماهنگ · قدرت و دفاع +{stats.set_bonus.bonus_percent}٪</span></div>:null}
  {weakest?<div className="sector-smart-tip"><span>پیشنهاد هوشمند</span><b>ضعیف‌ترین بخش: {SLOT_INFO[weakest.slot]?.[0]} — برای افزایش Power Score ارتقایش بده.</b></div>:null}
  <div className="sector-loadout__actions">{[1,2,3].map(slot=><div key={slot}><b>چینش {slot}</b><button disabled={busy} onClick={()=>onCommand('save_loadout',{slot})}>ذخیره</button><button disabled={busy} onClick={()=>onCommand('apply_loadout',{slot})}>فعال‌سازی</button></div>)}</div>
  <div className="sector-parts"><header><div><small>ROBOT COMPONENTS</small><h3>سامانه قطعات</h3></div><span>{equipped.size}/۸ اسلات فعال</span></header>{Object.entries(SLOT_INFO).map(([slot,[title,detail]])=>{const item=equipped.get(slot);return <article key={slot} className={item?`rarity--${item.rarity}`:'empty'}><div className="sector-part__art">{item?<ShopItemArt item={item} size={76}/>:<span>＋</span>}</div><div className="sector-part__info"><small>{title}</small><b>{item?.title||'جایگاه خالی'}</b><span>{item?`سطح ${item.gear_level}/۱۰ · سلامت ${item.wear}٪`:detail}</span>{item?.upgrading?<Timer seconds={item.upgrade_remaining_seconds}/>:null}</div><div className="sector-part__power">{item?<><b>⚔ {item.effective_power}</b><b>🛡 {item.effective_defense}</b></>:null}</div><div className="sector-part__buttons">{item?<><button disabled={busy||item.upgrading||item.gear_level>=10} onClick={()=>onCommand('upgrade_gear',{key:item.id})}>{item.upgrading?'در حال ارتقا':item.gear_level>=10?'حداکثر سطح':`ارتقا · ${item.upgrade_cost} سکه`}</button><button disabled={busy||item.wear>=100} onClick={()=>onCommand('repair_gear',{key:item.id})}>تعمیر</button></>:<button onClick={()=>document.querySelector('.sector-shop-categories')?.scrollIntoView({behavior:'smooth'})}>انتخاب قطعه</button>}</div></article>})}</div>
  <div className="sector-owned-parts"><header><div><small>OWNED COMPONENTS</small><h3>قطعات قابل جایگزینی</h3></div><span>{shop.filter(x=>x.owned).length} قطعه</span></header><div>{shop.filter(x=>x.owned).map(item=><button key={item.id} className={`rarity--${item.rarity}${item.equipped?' active':''}`} disabled={busy||item.equipped} onClick={()=>onEquip(item)}><span><ShopItemArt item={item} size={72}/></span><b>{item.title}</b><small>{SLOT_INFO[item.slot]?.[0]||item.category} · سطح {item.gear_level}</small><i>⚔ {item.effective_power} · 🛡 {item.effective_defense}</i><strong>{item.equipped?'فعال':'جایگزین کن'}</strong></button>)}</div></div>
  <div className="sector-power-source"><b>قدرت من از کجا آمده؟</b><span>تجهیزات فعال، سطح و سلامت هر قطعه، ساختمان کارگاه و پاداش ست‌ها مستقیماً در Power Score محاسبه می‌شوند.</span></div>
 </section>
}
