import {useEffect,useState} from 'react'
import SectorIcon from '../ui/SectorIcon'

function Timer({seconds}){const [left,setLeft]=useState(Math.max(0,Number(seconds||0)));useEffect(()=>{setLeft(Math.max(0,Number(seconds||0)));const id=setInterval(()=>setLeft(v=>Math.max(0,v-1)),1000);return()=>clearInterval(id)},[seconds]);const d=Math.floor(left/86400),h=Math.floor(left%86400/3600),m=Math.floor(left%3600/60),s=left%60;return <time>{d?`${d} روز · `:''}{[h,m,s].map(x=>String(x).padStart(2,'0')).join(':')}</time>}

export default function SectorCommandCenter({data,meta,busy,onCommand,onNavigate,onClaim}){
 const ex=data?.expansion||{},tutorial=ex.tutorial||{},missions=meta?.missions||[],quests=meta?.quests||[],event=ex.event||{},materials=ex.materials||{}
 const nextMission=missions.find(x=>x.complete&&!x.claimed)||missions.find(x=>!x.complete)
 return <div className="sector-command">
  {!tutorial.complete?<section className="glass sector-onboarding"><header><div><small>راهنمای شروع هوشمند</small><h3>راه‌اندازی {data?.pet?.name}</h3></div><b>{tutorial.completed||0}/۵</b></header><div className="sector-onboarding__steps">{(tutorial.steps||[]).map((x,i)=><button key={x.id} className={x.done?'done':tutorial.current?.id===x.id?'current':''} onClick={()=>!x.done&&onNavigate(x.action)}><i>{x.done?'✓':i+1}</i><span><b>{x.title}</b><small>{x.detail}</small></span></button>)}</div>{tutorial.completed>=2&&!data?.pet?.inventory?.['tutorial:reward']?<button className="btn btn-gold" disabled={busy} onClick={()=>onCommand('tutorial_reward')}>دریافت بسته شروع · ۱۵۰ سکه + ۶۰ XP</button>:null}</section>:null}

  <section className="glass sector-mission-hq"><header><div><small>MISSION CONTROL</small><h3>مرکز مأموریت</h3><p>{nextMission?`حرکت پیشنهادی: ${nextMission.title}`:'همه مأموریت‌های فعلی کامل شده‌اند؛ سراغ داستان یا رویداد برو.'}</p></div><SectorIcon name="mission" size={28}/></header><div>{missions.map(x=><article key={x.id} className={x.complete?'done':''}><div><b>{x.title}</b><span>{x.kind==='weekly'?'هفتگی':'روزانه'} · {x.progress}/{x.target}</span></div><Timer seconds={x.reset_seconds}/><small>{x.reward?.coins} سکه · {x.reward?.xp} XP</small>{x.complete&&!x.claimed?<button disabled={busy} onClick={()=>onClaim('mission',x.id)}>گرفتن جایزه</button>:<button disabled={x.complete} onClick={()=>onNavigate(x.metric==='game'?'open_games':'open_care')}>{x.complete?'انجام شد':'انجام مأموریت'}</button>}</article>)}</div><details><summary>دستاوردهای بلندمدت</summary>{quests.map(x=><div className="sector-quest" key={x.id}><span><b>{x.title}</b><small>{x.hint}</small></span>{x.complete&&!x.claimed?<button onClick={()=>onClaim('quest',x.id)}>دریافت</button>:<i>{x.complete?'✓':'قفل'}</i>}</div>)}</details></section>

  <section className="glass sector-economy-guide"><header><div><small>ECONOMY MAP</small><h3>سکه را کجا بگیرم و خرج کنم؟</h3></div><b>{Number(ex.coins||0).toLocaleString('fa-IR')} سکه</b></header><div>{(ex.economy||[]).map(x=><article key={x.title}><span><b>{x.title}</b><small>{x.source}</small></span><i>{x.cost?`${x.cost} سکه`:'رایگان'}</i><strong>{x.result}</strong></article>)}</div></section>

  <section className="glass sector-base"><header><div><small>SECTOR BASE</small><h3>پایگاه سکتور</h3><p>ساختمان‌ها مزیت دائمی می‌دهند و ارتقای آن‌ها زمان‌دار است.</p></div><span>🛰️</span></header><div className="sector-base__grid">{(ex.base||[]).map(x=><article key={x.id}><i>{x.icon}</i><div><b>{x.title}</b><small>سطح {x.level}/{x.max_level} · {x.perk}</small></div>{x.upgrading?<span><Timer seconds={x.remaining_seconds}/></span>:<button disabled={busy||x.level>=x.max_level} onClick={()=>onCommand('upgrade_base',{key:x.id})}>{x.level>=x.max_level?'حداکثر':`ارتقا · ${x.next_cost} سکه`}</button>}</article>)}</div></section>

  <section className="glass sector-forge"><header><div><small>FORGE & SALVAGE</small><h3>کارخانه قطعات</h3></div><div><b>{materials.scrap||0}</b><span>مواد اولیه</span><b>{materials.crystal||0}</b><span>کریستال</span></div></header><p>قطعات اضافه را بازیافت کن؛ هر ۳ ماده اولیه یک قطعه Rare یا Epic تازه می‌سازد.</p><button className="btn btn-primary" disabled={busy||Number(materials.scrap||0)<3} onClick={()=>onCommand('forge')}>ساخت قطعه تازه · ۳ ماده</button></section>

  <section className="glass sector-live-event"><header><div><small>LIMITED EVENT</small><h3>{event.title}</h3><p>{event.detail}</p></div><Timer seconds={event.remaining_seconds}/></header><div className="sector-live-event__bar"><i style={{width:`${Math.min(100,Number(event.progress||0)/Math.max(1,Number(event.goal||1))*100)}%`}}/></div><footer><span>{event.progress||0}/{event.goal||0} کریستال مأموریت</span><b>{event.coins||0} سکه + {event.material||0} کریستال</b></footer><button className="btn btn-gold" disabled={busy||!event.complete||event.claimed} onClick={()=>onCommand('claim_event')}>{event.claimed?'دریافت شد':event.complete?'دریافت جایزه رویداد':'برای پیشرفت بازی و مراقبت کن'}</button></section>

  <section className="glass sector-story-branches"><small>BRANCHING STORY</small><h3>سرنوشت سکتور را انتخاب کن</h3><p>مسیر انتخابی روی شخصیت، مأموریت و توانایی‌های آینده اثر می‌گذارد و قابل تغییر است.</p><div>{[['guardian','🛡️','نگهبان','زره و دفاع'],['explorer','🧭','کاوشگر','رویداد و کشف'],['engineer','⚙️','مهندس','ساخت و ارتقا']].map(x=><button key={x[0]} className={ex.story_branch===x[0]?'active':''} onClick={()=>onCommand('story_branch',{key:x[0]})}><i>{x[1]}</i><b>{x[2]}</b><small>{x[3]}</small></button>)}</div></section>
 </div>
}
